### ISSUE TITLE
'err' not referenced before assignment

### ISSUE THREAD

**Issue by RoseApollo** [barrald/strava-uploader#17]
gives error:

`Traceback (most recent call last):
  File "uploader.py", line 327, in <module>
    main()
  File "uploader.py", line 297, in main
    if upload_gpx(client, gpxfile, strava_activity_type, row['Notes']):
  File "uploader.py", line 178, in upload_gpx
    logger.error("Problem raised: {}\nExiting...".format(err))
UnboundLocalError: local variable 'err' referenced before assignment`

**Comment by barrald** [comment]
Closed by #18
