### ISSUE TITLE
Flask /auth cannot return a dict

### ISSUE THREAD

**Issue by jordansafer** [barrald/strava-uploader#7]
Flask error- /auth function cannot return a dict. I fixed this by printing the token and returning a string instead

**Comment by barrald** [comment]
Thanks Jordan! Do you have a PR with the fix (and/or the fix to #8 ) you can submit?

**Comment by jordansafer** [comment]
Hey, my fix for this one is kind of sloppy- I'll send the fix for 8 in the mean time
