### ISSUE TITLE
Unsupported scope value(s): {'view_private,write'}

### ISSUE THREAD

**Issue by jordansafer** [barrald/strava-uploader#8]
I tried to fix this by changing scope to "activity:write", which was listed on the strava website

**Comment by jordansafer** [comment]
Yup, it looks like someone just added the fix yesterday! No worries, I just used my branch when I needed it and I think the issue helped other people who ran into this

**Comment by barrald** [comment]
Yes it looks like it. Really appreciate you contributing and helping out
others!
